const express = require("express");
const userRoutes = require("./userRoutes");
const cafeRoutes = require("./cafeRoutes");
const reserveRoutes = require("./reserveRoutes");
const tableRoutes = require("./tableRoutes");
const router = express.Router();
router.use("/users", userRoutes);
router.use("/cafes", cafeRoutes);
router.use("/reserves", reserveRoutes);
router.use("/tables", tableRoutes);
module.exports = router;
